language: java

jdk:
  - oraclejdk8


install:

    - sudo apt-get -qq update
    - sudo apt-get install gnat
    - cd /usr/local
    - git clone --depth 1 https://github.com/ghdl/ghdl.git ghdl
    - cd ghdl
    - mkdir install-ghdl-mcode
    - cd .. 
    - pwd
    - ./configure --prefix=/usr/local/install-ghdl-mcode

#    - mkdir build-mcode
#    - cd build-mcode
#    - ../configure --prefix=../../install-ghdl-mcode/
#    - configure --prefix=/opt/ghdl
     - make
     - make install
  #  - pwd
    - cd ../../
    - export PATH=$PATH:/usr/local/install-ghdl-mcode/bin/
    - echo $PATH




script: mvn clean install

