language: java

jdk:
  - oraclejdk8

addons:
      apt:
        packages:
- gnat

install:
    - cd /usr/local
    - git clone --depth 1 https://github.com/ghdl/ghdl.git ghdl
    - cd ghdl
    - mkdir build-mcode
    - cd build-mcode
    - ../configure --prefix=../../install-ghdl-mcode/
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-mcode/bin/

script: mvn clean install

