language: java

jdk:
  - oraclejdk8


install:

    - sudo apt-get -qq update
 #   - sudo apt-get install gnat
 #   - wget https://github.com/ghdl/ghdl/archive/v0.35.tar.gz
 #   - tar xzvf v0.35.tar.gz
 #   - cd ghdl-0.35
 #   - ./configure
 #   - make
 #   - sudo make install
 #   - cd ..
    - sudo apt-get install ghdl gtkwave



script: mvn clean install

